### ISSUE TITLE
fastlane-deploy command does not exist

### ISSUE THREAD

**Issue by jim-at-jibba** [CircleCI-Public/android-orb#61]
### Orb version
circleci/android@2.1.2

### What happened
fastlane-deploy command does not exist

### Expected behavior
fastlane-deply command to exist

**Comment by ryanbourdais** [comment]
Hi @jim-at-jibba this will be resolved with the release of the next orb version, for the time being fastlane has been added to the android images and can still be utilized manually so long as you have configured its use in your repository

**Comment by merwok** [comment]
Configured its use how?

With the android orb v2.1.1, using the job or the command is not possible

Following the easy way from the doc:
> Cannot find a definition for job named android/deploy-to-play-store

Switching to calling individual commands:
> Cannot find a definition for command named android/fastlane-deploy

**Comment by ryanbourdais** [comment]
@merwok @jim-at-jibba I believe both of you have received the usage of the fastlane command from [this piece of documentation](https://circleci.com/docs/deploy-android-applications/). Currently, the functionality is there but is just waiting to be released. I plan on cutting a new release by the end of this week that will add all of this functionality to the orb

**Comment by ryanbourdais** [comment]
@merwok @jim-at-jibba I cut release v2.2.0 today which now includes the commands and job for deploying an android app to the play store. You can find the documentation for this [here](https://circleci.com/developer/orbs/orb/circleci/android#jobs-deploy-to-play-store). I'm going to close this issue here as now the `fastlane-deploy` command does exist. Please do not hesitate to open a new issue if you experience problems with this new release.
